---
hostname: labvm
existing_user: devasc
existing_user_pass: Cisco123!
ciscouser: devasc
ciscopass: Cisco123!
ansible_become_password: "{{ existing_user_pass }}"
user_home: "/home/{{ existing_user }}"
desktop_path: "{{ user_home }}/Desktop"
ubuntuversion: focal
user_groups:
  - wireshark
  - docker