---
- name: Download and install a .deb package on Ubuntu 24
  hosts: ubuntu_hosts
  become: true
  vars:
    deb_url: "https://example.com/path/to/package.deb"
    deb_file: "/tmp/package.deb"

  tasks:


- name: Download .deb file
  ansible.builtin.get_url:
    url: "https://archive.org/download/packettracer900/CiscoPacketTracer_900_Ubuntu_64bit.deb"
    dest: "/tmp/CiscoPacketTracer_900_Ubuntu_64bit.deb"
    mode: '0644'

- name: Install .deb package
  ansible.builtin.apt:
    deb: "/tmp/CiscoPacketTracer_900_Ubuntu_64bit.deb"
    state: present

- name: Clean up .deb file (optional)
  ansible.builtin.file:
    path: "/tmp/CiscoPacketTracer_900_Ubuntu_64bit.deb"
    state: absent
