---
- name: apt_update
  apt:
    update_cache: yes
- name: restart_gdm
  service:
    name: gdm3
    state: restarted
- name: restart_systemd_logind
  service:
    name: systemd-logind
    state: restarted
- name: apply_netplan
  command: netplan apply
- name: reload_systemd
  command: systemctl daemon-reload